### ISSUE TITLE
MaxUtilization Exception

### ISSUE THREAD

**Issue by 5corp** [fsdonks/m4#1]
Data on other network is throwing Exception [:negative-wait-time] marathon.ces/behavior/change-state-beh

**Comment by 5corp** [comment]
RC unit 14 forensics:

day-of 1760 BOG Budget 105
day-of 1792 BOG Budget 105
1792 Policy Change from MaxUtilization_Enabler (policy BOG budget of 365) to TAA19-23_RC14 (policy BOG budget of 270)
day-of 1793 BOG Budget 10

**Comment by fs-tom** [comment]
Couldn't reproduce with notional  data.  Run completed with current snapshot (4.14).  Is this the same data?

**Comment by fs-craig** [comment]
Yea.  The notional data I uploaded will complete, but it reproduces the 10 BOG budget remaining after the policy change which may or may not be causing an exception on high side.  

I was going to try shifting that second demand record tomorrow so that the unit deploys in it's life cycle when it has 10 BOG remaining.  That might cause the exception.

**Comment by fs-tom** [comment]
Understood.  I'll work with that.  We shouldn't have 10 BB, I think.

**Comment by fs-tom** [comment]
relevant facts (after reading an entity-trace): 
goes to fill on day 1, max ut.
gets sent home with 105 budget left, day 260 (abrupt withdraw, does not followon).
Since overlap is 0 for policy, able to recover.
recovers immediately, becomes Available.
Dwells for 9, until policy  change "positions" him at reset (does not actually 0 out) with a cycletime of 270.
budget is not modified (cycle not completed, never actually reset).
Stays that way for remainder.

Shifting demand to 2190 reproduces problem (negative wait).

**Comment by 5corp** [comment]
Fixed in commit 1c467046376fba5956bc48104ab3c423318c105a "Reset function now resets bogbudget too"
