### ISSUE TITLE
Account for overlap in deployability / reset criteria for policy change

### ISSUE THREAD

**Issue by fs-tom** [fsdonks/m4#3]
Possible to construct policy changes that lead to a state where bog-time (bogremaining - overlap) is negative.

Add check to policy change (or update deployable predicate) to ensure that entities automatically reset if they can't feasibly bog in the next policy.

**Comment by 5corp** [comment]
There is a note in marathon.ces.behavior on line 2032 about these issues when changing from a policy with a longer BOG budget to a shorter BOG budget.  infeasible-bog-reset on line 1931 looks like it is meant to handle this through policy-change-deployability-check at the end of apply-policy-change.

In order to debug this, I think I need a better idea of the behavior stuff like befn, the bheaviorenv, and the -> behavior utility functions, so I'm reading through your docs on some of this now.

I'm leaving at 12 today and Monday is my CWS day now, but I'll see you in the office on Tuesday.

**Comment by 5corp** [comment]
Fixed in commit 1c467046376fba5956bc48104ab3c423318c105a "Reset function now resets bogbudget too"
